---
# tasks file for ansible-prometheus-exporters

- import_tasks: node.yml
  when: node_exporter_enable
  tags: [prometheus-exporters, node-exporter]

- import_tasks: postgresql.yml
  when: postgres_exporter_enable
  tags: [prometheus-exporters, postgresql-exporter, postgres-exporter]

- import_tasks: greenplum.yml
  when: greenplum_exporter_enable
  tags: [prometheus-exporters, greenplum-exporter]

- import_tasks: clickhouse.yml
  when: clickhouse_exporter_enable
  tags: [prometheus-exporters, clickhouse-exporter]
